name: handwritingspeechrecognition
description: Techniki Multimedialne PW(OKNO)-projekt zaliczeniowy

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  tflite: ^1.0.4
  image: ^2.1.4
  speech_to_text: ^2.3.0
  highlight_text: ^0.7.2
  avatar_glow: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/converted_mnist_model.tflite
    - assets/labels.txt
